"""Description of the changes

Revision ID: 09692d4e21b4
Revises: 
Create Date: 2023-07-10 21:34:15.864942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09692d4e21b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
