"""change relations

Revision ID: 4f7169ab0447
Revises: 42c3ed8bf5a4
Create Date: 2023-07-12 13:33:28.313103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7169ab0447'
down_revision = '42c3ed8bf5a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
