"""add post_like

Revision ID: e77188b83d3a
Revises: 09692d4e21b4
Create Date: 2023-07-11 22:46:20.786672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77188b83d3a'
down_revision = '09692d4e21b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislikes')
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
